# DevForgeKit bash completion - generated by scripts/generate-completions.mjs, do not hand-edit.
_devforgekit_completions() {
    local cur prev words cword
    _init_completion || return

    if [[ ${cword} -eq 1 ]]; then
        COMPREPLY=($(compgen -W "check dashboard ui doctor install bootstrap self-update upgrade update validate new create collection component info registry search stats snapshot snap workspace compatibility repair fix heal ai theme plugin graph deps benchmark bench perf package packages pkg config profile recipe backup clean cleanup inventory preferences prefs release report restore services env explain hello rc-validate uninstall" -- "$cur"))
        return 0
    fi

    case "${words[1]}" in
        collection)
            COMPREPLY=($(compgen -W "list info install" -- "$cur"))
            return 0
            ;;
        component)
            COMPREPLY=($(compgen -W "list export info doctor install validate repair update reinstall uninstall remove" -- "$cur"))
            return 0
            ;;
        registry)
            COMPREPLY=($(compgen -W "generate stats verify doctor audit format lint" -- "$cur"))
            return 0
            ;;
        snapshot|snap)
            COMPREPLY=($(compgen -W "create restore list inspect verify diff export delete explain" -- "$cur"))
            return 0
            ;;
        workspace)
            COMPREPLY=($(compgen -W "create list show metadata switch deactivate delete rename clone search verify repair export import diff health snapshot rollback env ssh git-capture shell-init compatibility benchmark" -- "$cur"))
            return 0
            ;;
        compatibility)
            COMPREPLY=($(compgen -W "scan check explain repair graph update export" -- "$cur"))
            return 0
            ;;
        repair|fix|heal)
            COMPREPLY=($(compgen -W "run install scan plan explain explain-issues verify rollback rollback-repair rollback-list history export delete clean benchmark" -- "$cur"))
            return 0
            ;;
        ai)
            COMPREPLY=($(compgen -W "chat doctor explain review compare generate analyze summarize optimize repair planner models providers setup key provider model history status health fix stats export import reset benchmark" -- "$cur"))
            return 0
            ;;
        theme)
            COMPREPLY=($(compgen -W "list use preview random export import gallery" -- "$cur"))
            return 0
            ;;
        plugin)
            COMPREPLY=($(compgen -W "list info run create test build package publish install validate quality doctor trust keygen" -- "$cur"))
            return 0
            ;;
        graph|deps)
            COMPREPLY=($(compgen -W "open cache search explain export verify stats path impact conflicts orphan focus history" -- "$cur"))
            return 0
            ;;
        benchmark|bench|perf)
            COMPREPLY=($(compgen -W "quick full standard compare history export delete explain trend intelligence report" -- "$cur"))
            return 0
            ;;
        package|packages|pkg)
            COMPREPLY=($(compgen -W "analyze info tree graph orphan duplicates unused outdated recommend impact search compare history export" -- "$cur"))
            return 0
            ;;
        config)
            COMPREPLY=($(compgen -W "get set list" -- "$cur"))
            return 0
            ;;
        profile)
            COMPREPLY=($(compgen -W "list show use install create export import search publish" -- "$cur"))
            return 0
            ;;
        recipe)
            COMPREPLY=($(compgen -W "list show install import create search publish" -- "$cur"))
            return 0
            ;;
        env)
            COMPREPLY=($(compgen -W "doctor validate list regenerate graph shells diff history watch snapshot restore" -- "$cur"))
            return 0
            ;;
    esac
}
complete -F _devforgekit_completions devforgekit
