#compdef devforgekit
# DevForgeKit zsh completion - generated by scripts/generate-completions.mjs, do not hand-edit.
_devforgekit() {
    local -a commands
    if (( CURRENT == 2 )); then
        _values 'command' \
        'check:Fast PASS/WARNING/FAIL health check'
        'dashboard|ui:Open the interactive terminal dashboard (also: run devforgekit with no arguments)'
        'doctor:Deep diagnostics + health score (forwards flags like --fix to scripts/doctor.sh)'
        'install|bootstrap:Full provision: Homebrew, mise, dotfiles, editors, services'
        'self-update|upgrade:Update DevForgeKit itself: git pull, npm install, config migration, plugin updates, changelog'
        'update:Upgrade every managed toolchain, restart services'
        'validate:Validate this repo'\''s own scripts/configs'
        'new|create:Generate a complete, production-ready project for a supported stack (no arguments = pick interactively)'
        'collection:List, inspect, or install curated component collections'
        'component:List, search, install, validate, repair, update, or uninstall registry components'
        'info:Rich, human-readable component info (description, deps, license, install size, quality score, alternatives)'
        'registry:Rebuild the registry index/docs, or show registry analytics'
        'search:Search components by name, description, category, tags, or aliases'
        'stats:Show installed components, disk usage, outdated packages, and a health score'
        'snapshot|snap:Environment Snapshot & Restore - capture, restore, inspect, and diff portable .dfk archives'
        'workspace:Manage isolated development environments (git/ssh/env/docker/k8s/cloud/shell identity, switched with one command)'
        'compatibility:Validate whether installed tools actually work together (see docs/CompatibilityEngine.md)'
        'repair|fix|heal:Intelligent Repair Engine - detect, analyze, plan, and safely repair environment issues'
        'ai:The AI Development Assistant - understands this environment, doesn'\''t invent it (see docs/AIAssistant.md)'
        'theme:Manage TUI themes (list, preview, use, export, import, gallery)'
        'plugin:The Plugin SDK - discover, run, and build DevForgeKit plugins'
        'graph|deps:Development Environment Graph - visualize and analyze your entire dev ecosystem'
        'benchmark|bench|perf:Benchmark Engine - measure development environment performance'
        'package|packages|pkg:Package Intelligence & Analytics - analyze installed development tools'
        'config:Get, set, or list DevForgeKit configuration'
        'profile:Manage bootstrap profiles (Layer 1) and environment profiles (Layer 2)'
        'recipe:Manage recipes - reusable, one-command environment workflows (install + configure + verify)'
        'backup:Capture live config into the repo, commit+push if changed'
        'clean|cleanup:Reclaim disk space across every cache'
        'inventory:Generate machine inventory reports under reports/ (forwards flags to scripts/inventory.sh)'
        'preferences|prefs:backup|restore|status for macOS UI preferences'
        'release:patch|minor|major version release (bump VERSION, draft CHANGELOG, tag, push)'
        'report:Generate a system report at reports/system-report.txt'
        'restore:Restore dotfiles/editors from the repo (no packages/services)'
        'services:start|stop|restart|status for local services (PostgreSQL, MySQL, Redis)'
        'env:Environment Configuration Engine - PATH/variables/shell hooks generated from package metadata, never hand-edited'
        'explain:Why a component is installed, what depends on it, and whether it'\''s safe to remove'
        'hello:Print a greeting from the hello-world example plugin'
        'rc-validate:Distribution Verification & RC Validation - GitHub Release/npm/Homebrew/install/smoke tests + docs/RCValidationReport.md (see RELEASE.md)'
        'uninstall:Remove what DevForgeKit installed - packages, VS Code/Cursor extensions, configuration, services (see '\''uninstall --help'\'')'
        return
    fi

    case "${words[2]}" in
        collection)
            _values 'subcommand' \
            'list:List every collection'
            'info:Show a collection'\''s member components'
            'install:Install every component in a collection, resolving dependencies'
            ;;
        component)
            _values 'subcommand' \
            'list:List every component, grouped by category (add --status for live installed/health/version/provider)'
            'export:Export a Markdown report: every component'\''s live status, or one component'\''s full doctor report with <name>'
            'info:Unified component status: install/version/provider/binary, environment health, dependencies, capabilities (--json for the raw manifest)'
            'doctor:Diagnose one component: install status, environment health, dependency status, conflicts'
            'install:Install one or more components, resolving dependencies (interactive picker if none given)'
            'validate:Run a component'\''s validate command'
            'repair:Run a component'\''s repair command'
            'update:Run a component'\''s update command'
            'reinstall:Uninstall then install a component fresh'
            'uninstall|remove:Run a component'\''s uninstall command'
            ;;
        registry)
            _values 'subcommand' \
            'generate:Validate every manifest (including cross-references) and regenerate registry.json + docs/Registry.md'
            'stats:Registry analytics: totals, dependency graph, package manager/category/platform breakdown, duplicate aliases, orphaned manifests, metadata completeness'
            'verify:Check every registry package'\''s install status. Read-only by default (validates what'\''s already installed) - pass --install to actually attempt installing missing packages.'
            'doctor:Registry health check: broken formulas, missing commands, dead URLs, duplicates, untested packages'
            'audit:Registry health scorecard: coverage percentages across documentation/validation/aliases/architecture/compatibility, plus actionable recommendations'
            'format:Normalize every registry/*.yaml file'\''s key order, array style, and quoting to one canonical, deterministic form'
            'lint:Structural checks: schema violations, duplicate IDs/binaries/aliases, cyclic dependencies, orphan packages'
            ;;
        snapshot|snap)
            _values 'subcommand' \
            'create:Capture the current development environment into a portable .dfk archive'
            'restore:Restore an environment from a .dfk archive'
            'list:List available environment snapshots'
            'inspect:Display detailed information about a snapshot'
            'verify:Verify archive integrity, checksums, and compatibility'
            'diff:Compare two snapshots and show differences'
            'export:Copy a snapshot to another directory'
            'delete:Delete a snapshot'
            'explain:AI-powered explanation of a snapshot (requires AI provider)'
            ;;
        workspace)
            _values 'subcommand' \
            'create:Create a new workspace'
            'list:List every workspace (archived ones hidden unless --all)'
            'show:Show a workspace'\''s full configuration (defaults to the active workspace)'
            'metadata:Show rich structured metadata for a workspace (defaults to the active workspace)'
            'switch:Switch to a workspace: applies its git/ssh/docker/kubernetes/cloud identity and regenerates its shell export'
            'deactivate:Clear the active workspace (git/ssh/docker/kubernetes/cloud state is left as-is - see docs/WorkspaceManager.md)'
            'delete:Delete a workspace and all its local data (snapshots, secrets)'
            'rename:Rename a workspace'
            'clone:Clone a workspace'\''s configuration (never its secrets or snapshot history) under a new name'
            'search:Search workspaces by name, tag, owner, profile/recipe/collection/component, git identity, or cloud reference'
            'verify:Run a PASS/WARNING/FAIL health sweep across every subsystem a workspace declares (defaults to the active workspace)'
            'repair:Drop dangling references (a deleted profile/recipe/component/plugin) from a workspace'
            'export:Export a portable .tar.gz bundle of a workspace (secrets and snapshot history excluded)'
            'import:Import a workspace bundle'
            'diff:Compare two workspaces across all subsystems'
            'health:Show a quick health score with per-subsystem breakdown (defaults to the active workspace)'
            'snapshot:Point-in-time snapshots of a workspace'\''s configuration'
            'rollback:Roll back to a snapshot: takes a safety snapshot of the current state first, then restores - and if this is the active workspace, re-applies it live'
            'env:Manage a workspace'\''s environment variables (plain + AES-256-GCM-encrypted secrets)'
            'ssh:Manage a workspace'\''s SSH identities (~/.ssh/config Host blocks)'
            'git-capture:Capture this machine'\''s currently-configured git identity into a workspace'
            'shell-init:Install (or remove) the shell hook that sources the active workspace'\''s exported env vars/aliases/functions on new shells'
            'compatibility:Scan/repair a workspace'\''s resolved components for compatibility issues, and review its history'
            'benchmark:Benchmark core workspace operations. Read-only by default (metadata, health, verify, diff) - pass --ops to include mutating ones (snapshot, switch, restore, bundleExport, bundleImport), which write files and/or change your live git/ssh/docker/kubernetes/cloud-CLI identity'
            ;;
        compatibility)
            _values 'subcommand' \
            'scan:Scan components for compatibility issues (defaults to everything installed)'
            'check:Like scan, but scoped to exactly the given components and non-zero exit on any CRITICAL/UNSUPPORTED finding (for CI/scripting)'
            'explain:Explain one component'\''s compatibility requirements in detail'
            'repair:Generate (and, unless --dry-run, execute) a repair plan: install missing requirements, run recommended upgrades, and - only after confirmation - remove conflicting packages'
            'graph:Show the dependency graph for a set of components: missing deps, cycles, duplicate tool claims'
            'update:Re-validate the local compatibility rule database (schema + cross-references) - there is no remote rule source to fetch from yet'
            'export:Write a compatibility report to disk'
            ;;
        repair|fix|heal)
            _values 'subcommand' \
            'run:Run the full repair pipeline: scan → plan → repair → verify'
            'install:Check and repair the DevForgeKit CLI'\''s own install (global symlink, cli deps, failed packages from the last bootstrap.sh run)'
            'scan:Scan for issues across all DevForgeKit subsystems'
            'plan:Generate a repair plan from the last scan or a fresh scan'
            'explain:AI-powered explanation of detected issues (requires AI provider)'
            'explain-issues:Explain repair issues in human-readable format'
            'verify:Run post-repair verification (compatibility, health, workspaces, plugins)'
            'rollback:Roll back to a pre-repair snapshot'
            'rollback-repair:Roll back a specific repair by restoring file backups'
            'rollback-list:List repair records that can be rolled back'
            'history:List past repair records'
            'export:Export a repair record (json, markdown, html, csv)'
            'delete:Delete a repair record'
            'clean:Delete all repair history records'
            'benchmark:Benchmark repair engine performance (scan, plan, history)'
            ;;
        ai)
            _values 'subcommand' \
            'chat:Interactive chat, grounded in this machine'\''s real context'
            'doctor:AI-narrated diagnosis: what'\''s wrong, why, the fix, estimated time, and risk'
            'explain:Explain a topic (e.g. '\''compatibility'\'', a component name) in plain language'
            'review:Review the current project directory: architecture, dependencies, security, tests, CI, config'
            'compare:Compare two real registry components or Project Generator stacks, grounded only in their actual data'
            'generate:Describe a project in plain language; maps it onto a real Project Generator stack'
            'analyze:Analyze this environment'\''s overall health and configuration'
            'summarize:A quick plain-language status summary of this environment'
            'optimize:Suggest concrete optimizations for this environment or project'
            'repair:AI-narrated compatibility repair: explains the plan, then runs it the same way '\''compatibility repair'\'' does'
            'planner:Plan a learning/setup goal onto real registry collections/recipes/components (e.g. '\''I want to become a backend engineer'\'')'
            'models:List available models for the configured (or --provider) AI provider'
            'providers:Show every known AI provider'\''s configuration/health status'
            'setup:Guided AI provider setup — configure provider, model, and API key in one flow'
            'key:Manage API keys for AI providers (add, remove, list, test, rotate, export, import, migrate)'
            'provider:Switch between configured AI providers'
            'model:Manage AI models for the current provider'
            'history:Show the local AI event log (never chat contents - see docs/MemorySystem.md)'
            'status:Show the complete AI configuration status — provider, model, credentials, connection, validation'
            'health:A single AI health score (0-100%) with a per-check breakdown - the scorecard view of '\''ai status'\'''
            'fix:Automatically fix AI configuration issues — invalid models, missing defaults, recovery actions'
            'stats:Show AI usage statistics — request counts, most used model, average response time (local only)'
            'export:Export AI configuration (provider, model, endpoint, favorites) — never exports API keys'
            'import:Import AI configuration from a file — asks for missing API keys'
            'reset:Reset AI configuration — clears provider, model, endpoint, cache, and history. Keeps API keys unless confirmed.'
            'benchmark:Run a simple prompt against all configured providers and compare latency, tokens, and streaming'
            ;;
        theme)
            _values 'subcommand' \
            'list:List all available themes'
            'use:Switch to a theme immediately (persists to config)'
            'preview:Preview a theme in the dashboard without saving'
            'random:Switch to a random theme'
            'export:Export a theme to YAML (defaults to current theme)'
            'import:Import a custom theme from a YAML file'
            'gallery:Show a scrollable gallery of all themes in the dashboard'
            ;;
        plugin)
            _values 'subcommand' \
            'list:List every discovered plugin, including invalid/incompatible ones'
            'info:Show the full manifest for one plugin'
            'run:Run one of a plugin'\''s registered commands directly'
            'create:Scaffold a new plugin project (plugin.yml, commands/, hooks/, tests/, README.md)'
            'test:Validate a plugin'\''s manifest and run its tests/*.sh'
            'build:Validate, regenerate README.md, and write plugin.lock.json'
            'package:Package a plugin into a signed, checksummed .tar.gz'
            'publish:Stage a packaged plugin (+ checksum/signature) to a local or shared directory'
            'install:Install a plugin from a local .tar.gz or an http(s) URL'
            'validate:Validate a plugin'\''s manifest, scripts, and structure'
            'quality:Score a plugin'\''s quality across multiple categories'
            'doctor:Diagnose all discovered plugins for common issues'
            'trust:Add a third-party public key to this machine'\''s trusted-signers set'
            'keygen:(Re-)generate this machine'\''s local plugin-signing keypair'
            ;;
        graph|deps)
            _values 'subcommand' \
            'open:Build and display the environment graph'
            'cache:Show or clear the graph'\''s 30-minute build cache'
            'search:Search graph nodes by name, type, description, tag, or category'
            'explain:AI-powered explanation of a node in the graph (requires AI provider)'
            'export:Export graph (json, markdown, html, dot, mermaid, svg, tree, plantuml)'
            'verify:Verify graph integrity (missing nodes, cycles, conflicts, orphans)'
            'stats:Show graph statistics'
            'path:Find the shortest path between two nodes in the graph'
            'impact:Show what would be affected if a node were removed'
            'conflicts:Show all conflict edges in the graph'
            'orphan:Show orphan nodes (no connections in the graph), grouped by type'
            'focus:Extract a subgraph focused on a single node and its connections'
            'history:List past graph snapshots'
            ;;
        benchmark|bench|perf)
            _values 'subcommand' \
            'quick:Quick benchmark (~10-20s): CPU, disk, git, node, shell, memory'
            'full:Full benchmark (~2-5min): all categories including project generation'
            'standard:Standard benchmark (~30-60s): quick + docker, flutter, python, databases, package managers'
            'compare:Compare two benchmark results (by ID, or latest two if omitted)'
            'history:List past benchmark results'
            'export:Export a benchmark result (json, markdown, html, csv)'
            'delete:Delete a benchmark result'
            'explain:AI-powered explanation of benchmark results (requires AI provider)'
            'trend:Show trend analysis for a category (or overall) across history'
            'intelligence:Self-explaining benchmark report (no AI needed)'
            'report:Rich benchmark report with previous comparison'
            ;;
        package|packages|pkg)
            _values 'subcommand' \
            'analyze:Analyze all installed packages and build intelligence profiles'
            'info:Show complete information about a package'
            'tree:Show dependency tree for a package (or all installed packages)'
            'graph:Show dependency graph for a package (or all installed packages)'
            'orphan:Detect orphan packages that can potentially be removed'
            'duplicates:Detect duplicate packages and installations'
            'unused:Detect unused packages (alias for orphan)'
            'outdated:Detect outdated packages'
            'recommend:AI-powered package recommendations (requires AI provider)'
            'impact:Show the impact of a package on the environment'
            'search:Search installed packages by name, tag, description, category, workspace, recipe, or profile'
            'compare:Compare two analysis files and show changes'
            'history:List past package analysis records'
            'export:Export analysis (json, markdown, html, csv, dot, mermaid)'
            ;;
        config)
            _values 'subcommand' \
            'get:Print the effective value of a config key'
            'set:Persist a config key to ~/.devforgekit/config.json'
            'list:Print the fully merged, effective configuration'
            ;;
        profile)
            _values 'subcommand' \
            'list:List bootstrap profiles and environment profiles'
            'show:Show one profile'\''s definition (environment profile) or Brewfile contents (bootstrap profile)'
            'use:Set the default bootstrap profile (Layer 1 - forwards to scripts/profile.sh use)'
            'install:Install an environment profile (its collections + components), resolving dependencies'
            'create:Interactively build a new environment profile'
            'export:Export the currently-installed components as a profile (writes to a file if <name> is given, else prints YAML)'
            'import:Install a profile from an arbitrary YAML file (no registration needed)'
            'search:Search collection and profile names/descriptions (local only)'
            'publish:Publish a profile to the community registry (not yet available)'
            ;;
        recipe)
            _values 'subcommand' \
            'list:List every recipe'
            'show:Show a recipe'\''s resolved component list, configure/verify steps, and compatibility score'
            'install:Install a recipe: install its components, run its configure steps, then verify'
            'import:Install a recipe from an arbitrary YAML file (no registration needed)'
            'create:Interactively build a new recipe'
            'search:Search recipe names/descriptions/tags (local only)'
            'publish:Publish a recipe to the community registry (not yet available)'
            ;;
        env)
            _values 'subcommand' \
            'doctor:Validate the generated environment against the real filesystem/shell state'
            'validate:Alias for '\''env doctor'\'' - validate the current state without regenerating anything'
            'list:List tracked packages (version/provider/verified) and the merged PATH/variables/shell lines'
            'regenerate:Rebuild every generated shell file from the current registry + tracked-package state, and (re)install the shell hook'
            'graph:Dependency tree of tracked tools; with a name, show what removing it would affect'
            'shells:Per-shell writer capability matrix (what'\''s supported, partial, or planned)'
            'diff:What changed since a snapshot (default: the most recent one)'
            'history:Transaction log: what each regeneration changed (default: list available days)'
            'watch:Watch bin directories live: newly installed known tools are tracked and the environment regenerated as they appear (Ctrl-C to stop)'
            'snapshot:Environment snapshots - capture and inspect the tracked state and generated files'
            'restore:Restore a snapshot'\''s tracked state and regenerate from it (a safety snapshot of the current state is taken first)'
            ;;
    esac
}
_devforgekit
